module.exports = [
    "landing page",
    "register new user",
    "login user",
    "payment module",
    "track user ride",
    "track user order",
    "create new ride",
    "list all products",
    "delete item",
    "profile page",
    "search",
    "upload audio",
    "upload video",
    "play video",
    "chat",
    "analytics",
    "filter item",
];
