module.exports = [
    "landing page",
    "user authentication",
    "payment module",
    "product catalogues",
    "cart module",
    "GPS integration",
    "profile page",
    "search",
    "chat",
    "analytics",
    "admin dashboard",
    "notifications module",
    "recommendation engine",
];
